spring.application.name=hurryflex

spring.datasource.url=jdbc:mysql://localhost:3306/hurryflex_db
spring.datasource.username=root
spring.datasource.password=harrisonni18.

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework.security=DEBUG